package com.hbm.registry;

import java.util.HashMap;
import java.util.Map;

public final class LegacyMissileTabOrder {
    private static final String[] ORDER = {
            "machine_satlinker",
            "machine_forcefield",
            "struct_launcher",
            "struct_scaffold",
            "struct_launcher_core",
            "struct_launcher_core_large",
            "struct_soyuz_core",
            "machine_missile_assembly",
            "launch_pad",
            "launch_pad_rusted",
            "launch_pad_large",
            "compact_launcher",
            "launch_table",
            "soyuz_launcher",
            "sat_dock",
            "soyuz_capsule",
            "crate_supply",
            "machine_radar",
            "machine_radar_large",
            "radar_screen",
            "rangefinder",
            "designator",
            "designator_range",
            "designator_manual",
            "designator_arty_range",
            "missile_taint",
            "missile_micro",
            "missile_bhole",
            "missile_schrabidium",
            "missile_emp",
            "missile_generic",
            "missile_decoy",
            "missile_incendiary",
            "missile_cluster",
            "missile_buster",
            "missile_stealth",
            "missile_anti_ballistic",
            "missile_strong",
            "missile_incendiary_strong",
            "missile_cluster_strong",
            "missile_buster_strong",
            "missile_emp_strong",
            "missile_burst",
            "missile_inferno",
            "missile_rain",
            "missile_drill",
            "missile_shuttle",
            "missile_nuclear",
            "missile_nuclear_cluster",
            "missile_volcano",
            "missile_doomsday",
            "missile_doomsday_rusted",
            "missile_soyuz",
            "missile_soyuz_lander",
            "mp_thruster_10_kerosene",
            "mp_thruster_10_solid",
            "mp_thruster_10_xenon",
            "mp_thruster_15_kerosene",
            "mp_thruster_15_kerosene_dual",
            "mp_thruster_15_kerosene_triple",
            "mp_thruster_15_solid",
            "mp_thruster_15_solid_hexdecuple",
            "mp_thruster_15_hydrogen",
            "mp_thruster_15_hydrogen_dual",
            "mp_thruster_15_balefire_short",
            "mp_thruster_15_balefire",
            "mp_thruster_15_balefire_large",
            "mp_thruster_15_balefire_large_rad",
            "mp_thruster_20_kerosene",
            "mp_thruster_20_kerosene_dual",
            "mp_thruster_20_kerosene_triple",
            "mp_thruster_20_solid",
            "mp_thruster_20_solid_multi",
            "mp_thruster_20_solid_multier",
            "mp_stability_10_flat",
            "mp_stability_10_cruise",
            "mp_stability_10_space",
            "mp_stability_15_flat",
            "mp_stability_15_thin",
            "mp_stability_15_soyuz",
            "mp_s_20",
            "mp_fuselage_10_kerosene",
            "mp_fuselage_10_kerosene_camo",
            "mp_fuselage_10_kerosene_desert",
            "mp_fuselage_10_kerosene_sky",
            "mp_fuselage_10_kerosene_flames",
            "mp_fuselage_10_kerosene_insulation",
            "mp_fuselage_10_kerosene_sleek",
            "mp_fuselage_10_kerosene_metal",
            "mp_fuselage_10_kerosene_taint",
            "mp_fuselage_10_solid",
            "mp_fuselage_10_solid_flames",
            "mp_fuselage_10_solid_insulation",
            "mp_fuselage_10_solid_sleek",
            "mp_fuselage_10_solid_soviet_glory",
            "mp_fuselage_10_solid_cathedral",
            "mp_fuselage_10_solid_moonlit",
            "mp_fuselage_10_solid_battery",
            "mp_fuselage_10_solid_duracell",
            "mp_fuselage_10_xenon",
            "mp_fuselage_10_xenon_bhole",
            "mp_fuselage_10_long_kerosene",
            "mp_fuselage_10_long_kerosene_camo",
            "mp_fuselage_10_long_kerosene_desert",
            "mp_fuselage_10_long_kerosene_sky",
            "mp_fuselage_10_long_kerosene_flames",
            "mp_fuselage_10_long_kerosene_insulation",
            "mp_fuselage_10_long_kerosene_sleek",
            "mp_fuselage_10_long_kerosene_metal",
            "mp_fuselage_10_long_kerosene_taint",
            "mp_fuselage_10_long_kerosene_vap",
            "mp_fuselage_10_long_solid",
            "mp_fuselage_10_long_solid_flames",
            "mp_fuselage_10_long_solid_insulation",
            "mp_fuselage_10_long_solid_sleek",
            "mp_fuselage_10_long_solid_soviet_glory",
            "mp_fuselage_10_long_solid_bullet",
            "mp_fuselage_10_long_solid_silvermoonlight",
            "mp_fuselage_10_15_kerosene",
            "mp_fuselage_10_15_solid",
            "mp_fuselage_10_15_hydrogen",
            "mp_fuselage_10_15_balefire",
            "mp_fuselage_15_kerosene",
            "mp_fuselage_15_kerosene_camo",
            "mp_fuselage_15_kerosene_desert",
            "mp_fuselage_15_kerosene_sky",
            "mp_fuselage_15_kerosene_insulation",
            "mp_fuselage_15_kerosene_metal",
            "mp_fuselage_15_kerosene_decorated",
            "mp_fuselage_15_kerosene_steampunk",
            "mp_fuselage_15_kerosene_polite",
            "mp_fuselage_15_kerosene_blackjack",
            "mp_fuselage_15_kerosene_lambda",
            "mp_fuselage_15_kerosene_minuteman",
            "mp_fuselage_15_kerosene_taint",
            "mp_fuselage_15_kerosene_yuck",
            "mp_fuselage_15_solid",
            "mp_fuselage_15_solid_insulation",
            "mp_fuselage_15_solid_desh",
            "mp_fuselage_15_solid_soviet_glory",
            "mp_fuselage_15_solid_soviet_stank",
            "mp_fuselage_15_solid_faust",
            "mp_fuselage_15_solid_silvermoonlight",
            "mp_fuselage_15_solid_snowy",
            "mp_fuselage_15_solid_panorama",
            "mp_fuselage_15_solid_roses",
            "mp_fuselage_15_solid_mimi",
            "mp_fuselage_15_hydrogen",
            "mp_fuselage_15_hydrogen_cathedral",
            "mp_fuselage_15_balefire",
            "mp_fuselage_15_20_kerosene",
            "mp_fuselage_15_20_kerosene_magnusson",
            "mp_fuselage_15_20_solid",
            "mp_warhead_10_he",
            "mp_warhead_10_incendiary",
            "mp_warhead_10_buster",
            "mp_warhead_10_nuclear",
            "mp_warhead_10_nuclear_large",
            "mp_warhead_10_taint",
            "mp_warhead_10_cloud",
            "mp_warhead_15_he",
            "mp_warhead_15_incendiary",
            "mp_warhead_15_nuclear",
            "mp_warhead_15_nuclear_shark",
            "mp_warhead_15_nuclear_mimi",
            "mp_warhead_15_boxcar",
            "mp_warhead_15_n2",
            "mp_warhead_15_balefire",
            "mp_warhead_15_turbine",
            "mp_c_1",
            "mp_c_2",
            "mp_c_3",
            "mp_c_4",
            "mp_c_5",
            "sat_mapper",
            "sat_scanner",
            "sat_radar",
            "sat_laser",
            "sat_foeq",
            "sat_resonator",
            "sat_miner",
            "sat_lunar_miner",
            "sat_gerald",
            "sat_chip",
            "sat_interface",
            "sat_coord",
            "sat_designator",
            "sat_relay",
            "missile_kit",
            "loot_10",
            "loot_15",
            "loot_misc",
    };

    private static final Map<String, Integer> RANK = new HashMap<>();

    static {
        for (int i = 0; i < ORDER.length; i++) {
            RANK.put(ORDER[i], i);
        }
    }

    private LegacyMissileTabOrder() {
    }

    public static int rank(String path) {
        if (path == null || path.isEmpty()) {
            return Integer.MAX_VALUE;
        }
        if ("designator_arty".equals(path)) {
            path = "designator_arty_range";
        }
        Integer value = RANK.get(path);
        return value != null ? value : Integer.MAX_VALUE;
    }
}
