package com.hbm.items.machine;

import com.hbm.config.MachineConfig;
import com.hbm.items.machine.ItemRTGPelletDepleted.DepletedRTGMaterial;
import com.hbm.registry.ModItems;
import com.hbm.util.RTGUtil;
import net.minecraft.ChatFormatting;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;
import org.jetbrains.annotations.Nullable;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * 1.7.10 {@code ItemRTGPellet}: stack size 1, optional decay, Pu-238 trivia on use.
 */
public class ItemRTGPellet extends Item {
    public static final String TAG_DEPLETION = "PELLET_DEPLETION";
    public static final List<ItemRTGPellet> PELLET_LIST = new ArrayList<>();

    private static final String[] FACTS = {
            "One gram of Pu-238 costs $8,000.",
            "One gram of Pu-238 produces just under half a Watt of decay heat.",
            "The typical plutonium RTG contains close to eight kilograms of Pu-238.",
            "Pu-238's half life is 87.7 years.",
            "A plutonium RTG was used to power the New Horizons probe that visited Pluto in 2015.",
            "Po-210 can also be used for RTGs as it generates 140 W/g of decay heat due to its 138 day half life.",
            "Pa-231 is an isotope of protactinium that easily fissions, but it isn't quite fissile.",
            "Muons generated by matter-antimatter reactions can trigger nuclear fusion reactions at room temperature.",
            "Roughly 20% of U-235 nuclei will fail to fission when hit by a neutron. They become U-236 nuclei instead.",
            "Thorium reactors are really uranium reactors that convert thorium into U-233.",
            "Natural uranium consists of 99.284% U-238, 0.711% U-235, and 0.0055% U-234.",
            "Most nuclear reactors use uranium that has been enriched to 3-5% U-235.",
            "Uranium-based nuclear weapons require uranium enriched to at least 85-90% U-235.",
            "Depleted uranium is uranium that has had most of its U-235 removed. It is effectively pure U-238.",
            "In the 1920s, uranium was considered a useless byproduct of the production of radium.",
            "The Manhattan Project referred to refined natural uranium as tuballoy, enriched uranium as oralloy, and depleted uranium as depletalloy."
    };

    private final short heat;
    private boolean doesDecay;
    private DepletedRTGMaterial decayMaterial;
    private long lifespan;

    public ItemRTGPellet(int heatIn) {
        super(new Properties().stacksTo(1));
        this.heat = (short) heatIn;
        PELLET_LIST.add(this);
    }

    public ItemRTGPellet setDecays(DepletedRTGMaterial mat, long life) {
        this.doesDecay = true;
        this.decayMaterial = mat;
        this.lifespan = life;
        return this;
    }

    public long getMaxLifespan() {
        return lifespan;
    }

    public short getHeat() {
        return heat;
    }

    @Nullable
    public ItemStack getDecayItem() {
        return decayMaterial == null ? null : ItemRTGPelletDepleted.stack(decayMaterial);
    }

    public boolean getDoesDecay() {
        return doesDecay;
    }

    public static ItemStack handleDecay(ItemStack stack, ItemRTGPellet instance) {
        if (instance.getDoesDecay() && MachineConfig.rtgDecay()) {
            if (instance.getLifespan(stack) <= 0) {
                ItemStack decay = instance.getDecayItem();
                return decay == null ? ItemStack.EMPTY : decay;
            }
            instance.decay(stack);
        }
        return stack;
    }

    public void decay(ItemStack stack) {
        if (stack == null || stack.isEmpty() || !(stack.getItem() instanceof ItemRTGPellet pellet)) {
            return;
        }
        if (!pellet.getDoesDecay()) {
            return;
        }
        CompoundTag tag = stack.getTag();
        if (tag != null) {
            tag.putLong(TAG_DEPLETION, getLifespan(stack) - 1);
        } else {
            stack.getOrCreateTag().putLong(TAG_DEPLETION, getMaxLifespan());
        }
    }

    public long getLifespan(ItemStack stack) {
        if (stack == null || stack.isEmpty() || !(stack.getItem() instanceof ItemRTGPellet)) {
            return 0L;
        }
        CompoundTag tag = stack.getTag();
        if (tag != null && tag.contains(TAG_DEPLETION)) {
            return tag.getLong(TAG_DEPLETION);
        }
        stack.getOrCreateTag().putLong(TAG_DEPLETION, getMaxLifespan());
        return getMaxLifespan();
    }

    public static short getScaledPower(ItemRTGPellet fuel, ItemStack stack) {
        long max = fuel.getMaxLifespan();
        if (max <= 0L) {
            return fuel.getHeat();
        }
        return (short) Math.ceil(fuel.getHeat() * ((double) fuel.getLifespan(stack) / (double) max));
    }

    /** Depletion fraction 0 = new, 1 = spent (1.7 {@code getDurabilityForDisplay}). */
    public double depletionFraction(ItemStack stack) {
        long max = getMaxLifespan();
        if (max <= 0L) {
            return 0.0D;
        }
        return 1.0D - (double) getLifespan(stack) / (double) max;
    }

    @Override
    public InteractionResultHolder<ItemStack> use(Level level, Player player, InteractionHand hand) {
        ItemStack stack = player.getItemInHand(hand);
        if (!level.isClientSide && this == ModItems.PELLET_RTG.get()) {
            String fact = FACTS[level.random.nextInt(FACTS.length)];
            player.sendSystemMessage(Component.literal(fact).withStyle(ChatFormatting.YELLOW));
            level.playSound(null, player.getX(), player.getY(), player.getZ(),
                    SoundEvents.EXPERIENCE_ORB_PICKUP, SoundSource.PLAYERS, 1.0F, 1.0F);
        }
        return InteractionResultHolder.sidedSuccess(stack, level.isClientSide());
    }

    @Override
    public boolean isBarVisible(ItemStack stack) {
        return getDoesDecay() && getLifespan(stack) != getMaxLifespan();
    }

    @Override
    public int getBarWidth(ItemStack stack) {
        long max = getMaxLifespan();
        if (max <= 0L) {
            return 0;
        }
        return Math.round(13.0F * (float) ((double) getLifespan(stack) / (double) max));
    }

    @Override
    public void appendHoverText(ItemStack stack, @Nullable Level level, List<Component> tooltip, TooltipFlag flag) {
        tooltip.add(Component.translatable(getDescriptionId() + ".desc"));
        short shown = getDoesDecay() && MachineConfig.scaleRTGPower() ? getScaledPower(this, stack) : getHeat();
        tooltip.add(Component.translatable("desc.item.rtgHeat", shown));
        if (getDoesDecay()) {
            ItemStack decay = getDecayItem();
            if (decay != null && !decay.isEmpty()) {
                tooltip.add(Component.translatable("desc.item.rtgDecay", decay.getHoverName()));
            }
            tooltip.add(Component.literal(NumberFormat.getPercentInstance(Locale.US)
                    .format(maxSafe((float) getLifespan(stack), (float) getMaxLifespan()))));
            if (flag.isAdvanced()) {
                tooltip.add(Component.literal("EXTENDED INFO:"));
                tooltip.add(Component.literal(String.format(Locale.US, "%s / %s ticks",
                        getLifespan(stack), getMaxLifespan())));
                String[] left = RTGUtil.ticksToDate(getLifespan(stack));
                String[] maxLife = RTGUtil.ticksToDate(getMaxLifespan());
                tooltip.add(Component.literal(String.format(Locale.US,
                        "Time remaining: %s y, %s d, %s h", left[0], left[1], left[2])));
                tooltip.add(Component.literal(String.format(Locale.US,
                        "Maximum life: %s y, %s d, %s h", maxLife[0], maxLife[1], maxLife[2])));
            }
        }
    }

    private static float maxSafe(float amount, float total) {
        if (total <= 0.0F) {
            return 0.0F;
        }
        return amount / total;
    }
}
